### ISSUE TITLE
Speed up model reconstruction

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-model#21]
This is to reduce the modelling time from 2 s (current) to less than 1s.

**Comment by giuliavezzani** [comment]
To Do:

- [ ] collect several object superquadrics (with YCB)
- [ ] test the minimum number of points for the optimizer
- [ ] test to see the parameters and the performance

**Comment by giuliavezzani** [comment]
Several point clouds have been collected from the **YCB dataset**:

![20170405_105917](https://cloud.githubusercontent.com/assets/9597070/24697896/1be74642-19ef-11e7-9de4-2e27e74894ce.jpg)

The common element among these objects is that they can **easily represented** with **only one superquadric.**
For all the point clouds we use the following parameters for:

- point cloud filtering (**density filter**):

```
radius:                0.0002
nn-threshold:          20
```

- **superquadric reconstruction:

**


```
Optimizer points:    100
Tolerance :          0.0001
Nlp scaling method:  gradient-based
Mu strategy:         monotone
```

**Average execution time** on the point cloud is ** 0.19 s**.

Some examples of superquadrics:
![superq-2](https://cloud.githubusercontent.com/assets/9597070/24699517/8220e9ea-19f4-11e7-9daa-6562ab3c45a6.png)

### To Do

- [ ] Test on robot for checking point cloud filtering reliability
- [ ] Acquire point cloud color

**Comment by giuliavezzani** [comment]
We obtained **0.1 - 0.2 s** for each superquadric reconstruction, because even 25 points are enough for good models.

**Comment by pattacini** [comment]
Well, even though we got a nice advancement, I reckon it should be worth investigating whether we have still room for improvements 😉

**Comment by pattacini** [comment]
To be reported in Redmine.
