### ISSUE TITLE
Improve point cloud filtering

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-model#22]
This is to reduce failure cases, caused by noisy point clouds.

In particular, we experienced that sometimes the disparity map of the selected blob contains some noisy sub-blobs (usually belonging to the scene background). The filter currently implemented is not enough for detecting this type of failure, since it requires an a-priori tuning of the parameters.

We need to find a new filtering approach to be overlapped on the old filter.

**Comment by pattacini** [comment]
To be reported in Redmine.
