### ISSUE TITLE
Filter reconstructed object model

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/superquadric-model#23]
Instead of improving the point cloud filtering, we can directly work on **filtering the reconstructed model**.

**Comment by giuliavezzani** [comment]
## Tentative approach

Our module reconstructs a model each `t_rate` s.
Each model consists of 11 parameters: **5 for shape** (including **3 for dimensions**) and **6 for poses**.
We also can use the information about **bounding box** of the object: **center** and **corners**.

An possible approach in order to:

 - make the modelling process **stable**
 - and, discard **outliers**

could be the following.

- The **3 parameters** of the superquadric representing the **dimensions** are used for **detecting wrong models.** If the dimensions **change too much** (to be defined) between two consecutive reconstructions (or with respect to average values computed in a mobile window), the model should be rejected. Otherwise, the model should be considered ok, and, possibly, used to improve a **"average" model computed on a mobile window.**

-  The **6 parameters** representing the pose are compared with the information about the  current **bounding box** and with the estimation of the previous time instant (or of a average estimate).

**Comment by pattacini** [comment]
To be reported in Redmine.
