### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by pattacini** [robotology/superquadric-model#25]
Just a very tiny comment to improve the readability @giuliavezzani.

What about moving the tutorial in a dedicated markdown file under the example folder and then point at it from within the main README.md?

I'd rather replace **Example of Usage** with **Use Case**.

**Comment by pattacini** [comment]
Perhaps, we could also rename **example** in **tutorial**...

**Comment by giuliavezzani** [comment]
OK, that's a good idea!
