### ISSUE TITLE
Don't use "using namespace" within header files

### ISSUE THREAD

**Issue by pattacini** [robotology/superquadric-model#26]
Please, avoid relying on the `using namespace` within header files 😉 
I know I might be a bit fussy, but it's better to put forward this best practice.

**Comment by giuliavezzani** [comment]
Ah ok, I saw this use in other repositories and I thought it was a good practise. I'll remove them immediately!

**Comment by pattacini** [comment]
There's a very dangerous impact for library headers; nonetheless, it's better to be consistent also with modules, where the impact is quite limited.

**Comment by giuliavezzani** [comment]
Moved the `using::namespace` from the headers to src [1b0640e](https://github.com/robotology/superquadric-model/commit/1b0640e70386f236f5f1a7a3c8ee88be39d702ff).
