### ISSUE TITLE
Fix use of yarp::os::Property

### ISSUE THREAD

**Issue by pattacini** [robotology/superquadric-model#29]
`((dimensions x0 x1 x2) (exponents x3 x4) (center x5 x6 x7) (orientation x8 x9 x10 x11))`

must be rather:

`((dimensions (x0 x1 x2)) (exponents (x3 x4)) (center (x5 x6 x7)) (orientation (x8 x9 x10 x11)))`

Therefore, you must use the method `find` instead of `findGroup`.

**Comment by giuliavezzani** [comment]
Actually, the property structure is correct in the code, I made a mistake in the README.md (now fixed).
I also replaced the `find` method with `findGroup`.
