### ISSUE TITLE
Need for a more appropriate module name

### ISSUE THREAD

**Issue by pattacini** [robotology/superquadric-model#9]
Actually, we don't detect superquadrics; we rather extract them :wink:.
Therefore, make up a brand new name catching this underlying point.

**Comment by giuliavezzani** [comment]
What about `superquadric-extraction`? or `superquadric-modeling`?

**Comment by pattacini** [comment]
`superquadric-generate`?

**Comment by pattacini** [comment]
Or... `superquadric-model`

**Comment by giuliavezzani** [comment]
Ok, simpler and more effective!

**Comment by pattacini** [comment]
@giuliavezzani changed the repo name in `superquadric-model`.
Closing.
